### ISSUE TITLE
Link zur Dokumentation zeigt auf das e-Spirit Intranet

### ISSUE THREAD

**Issue by sosswa** [e-Spirit/firstspirit-module-parent-pom#1]
Hallo Kollegen,

könnt ihr mir bitte Zugriff auf euer Intranet gewähren, damit ich die Doku lesen kann? ;-)
Alternativ wäre es auch ok, wenn ihr die Doku mit in die readme.md packt.

Danke und Grüße
Sandro

**Comment by ps-espirit** [comment]
Hallo Sandro, 

ich werde asap die Readme.md ergänzen (danke für die Info :)) und auch die Licence noch hinzufügen.

Gruß und Danke,
Daniel

**Comment by ps-espirit** [comment]
Readme.md habe ich ergänzt und angepasst.
